package com.example.util

import com.example.ui.screens.AdminCountryInfo

object AllCountriesProvider {

    val allCountries: List<AdminCountryInfo> = listOf(
        AdminCountryInfo("US", "United States", "🇺🇸", "+1"),
        AdminCountryInfo("BD", "Bangladesh", "🇧🇩", "+880"),
        AdminCountryInfo("GB", "United Kingdom", "🇬🇧", "+44"),
        AdminCountryInfo("CA", "Canada", "🇨🇦", "+1"),
        AdminCountryInfo("IN", "India", "🇮🇳", "+91"),
        AdminCountryInfo("PK", "Pakistan", "🇵🇰", "+92"),
        AdminCountryInfo("CM", "Cameroon", "🇨🇲", "+237"),
        AdminCountryInfo("BO", "Bolivia", "🇧🇴", "+591"),
        AdminCountryInfo("SD", "Sudan", "🇸🇩", "+249"),
        AdminCountryInfo("NG", "Nigeria", "🇳🇬", "+234"),
        AdminCountryInfo("PH", "Philippines", "🇵🇭", "+63"),
        AdminCountryInfo("ID", "Indonesia", "🇮🇩", "+62"),
        AdminCountryInfo("KE", "Kenya", "🇰🇪", "+254"),
        AdminCountryInfo("ZA", "South Africa", "🇿🇦", "+27"),
        AdminCountryInfo("BR", "Brazil", "🇧🇷", "+55"),
        AdminCountryInfo("MY", "Malaysia", "🇲🇾", "+60"),
        AdminCountryInfo("AE", "United Arab Emirates", "🇦🇪", "+971"),
        AdminCountryInfo("SA", "Saudi Arabia", "🇸🇦", "+966"),
        AdminCountryInfo("EG", "Egypt", "🇪🇬", "+20"),
        AdminCountryInfo("DE", "Germany", "🇩🇪", "+49"),
        AdminCountryInfo("FR", "France", "🇫🇷", "+33"),
        AdminCountryInfo("RU", "Russia", "🇷🇺", "+7"),
        AdminCountryInfo("TR", "Turkey", "🇹🇷", "+90"),
        AdminCountryInfo("IT", "Italy", "🇮🇹", "+39"),
        AdminCountryInfo("ES", "Spain", "🇪🇸", "+34"),
        AdminCountryInfo("MX", "Mexico", "🇲🇽", "+52"),
        AdminCountryInfo("JP", "Japan", "🇯🇵", "+81"),
        AdminCountryInfo("CN", "China", "🇨🇳", "+86"),
        AdminCountryInfo("KR", "South Korea", "🇰🇷", "+82"),
        AdminCountryInfo("AU", "Australia", "🇦🇺", "+61"),
        AdminCountryInfo("SG", "Singapore", "🇸🇬", "+65"),
        AdminCountryInfo("TH", "Thailand", "🇹🇭", "+66"),
        AdminCountryInfo("VN", "Vietnam", "🇻🇳", "+84"),
        AdminCountryInfo("NP", "Nepal", "🇳🇵", "+977"),
        AdminCountryInfo("LK", "Sri Lanka", "🇱🇰", "+94"),
        AdminCountryInfo("AF", "Afghanistan", "🇦🇫", "+93"),
        AdminCountryInfo("DZ", "Algeria", "🇩🇿", "+213"),
        AdminCountryInfo("AR", "Argentina", "🇦🇷", "+54"),
        AdminCountryInfo("AT", "Austria", "🇦🇹", "+43"),
        AdminCountryInfo("AZ", "Azerbaijan", "🇦🇿", "+994"),
        AdminCountryInfo("BH", "Bahrain", "🇧🇭", "+973"),
        AdminCountryInfo("BY", "Belarus", "🇧🇾", "+375"),
        AdminCountryInfo("BE", "Belgium", "🇧🇪", "+32"),
        AdminCountryInfo("CL", "Chile", "🇨🇱", "+56"),
        AdminCountryInfo("CO", "Colombia", "🇨🇴", "+57"),
        AdminCountryInfo("CR", "Costa Rica", "🇨🇷", "+506"),
        AdminCountryInfo("HR", "Croatia", "🇭🇷", "+385"),
        AdminCountryInfo("CY", "Cyprus", "🇨🇾", "+357"),
        AdminCountryInfo("CZ", "Czech Republic", "🇨🇿", "+420"),
        AdminCountryInfo("DK", "Denmark", "🇩🇰", "+45"),
        AdminCountryInfo("EC", "Ecuador", "🇪🇨", "+593"),
        AdminCountryInfo("EE", "Estonia", "🇪🇪", "+372"),
        AdminCountryInfo("ET", "Ethiopia", "🇪🇹", "+251"),
        AdminCountryInfo("FI", "Finland", "🇫🇮", "+358"),
        AdminCountryInfo("GE", "Georgia", "🇬🇪", "+995"),
        AdminCountryInfo("GH", "Ghana", "🇬🇭", "+233"),
        AdminCountryInfo("GR", "Greece", "🇬🇷", "+30"),
        AdminCountryInfo("HK", "Hong Kong", "🇭🇰", "+852"),
        AdminCountryInfo("HU", "Hungary", "🇭🇺", "+36"),
        AdminCountryInfo("IS", "Iceland", "🇮🇸", "+354"),
        AdminCountryInfo("IQ", "Iraq", "🇮🇶", "+964"),
        AdminCountryInfo("IE", "Ireland", "🇮🇪", "+353"),
        AdminCountryInfo("IL", "Israel", "🇮🇱", "+972"),
        AdminCountryInfo("JO", "Jordan", "🇯🇴", "+962"),
        AdminCountryInfo("KZ", "Kazakhstan", "🇰🇿", "+7"),
        AdminCountryInfo("KW", "Kuwait", "🇰🇼", "+965"),
        AdminCountryInfo("LB", "Lebanon", "🇱🇧", "+961"),
        AdminCountryInfo("LY", "Libya", "🇱🇾", "+218"),
        AdminCountryInfo("LT", "Lithuania", "🇱🇹", "+370"),
        AdminCountryInfo("LU", "Luxembourg", "🇱🇺", "+352"),
        AdminCountryInfo("MO", "Macau", "🇲🇴", "+853"),
        AdminCountryInfo("MG", "Madagascar", "🇲🇬", "+261"),
        AdminCountryInfo("MV", "Maldives", "🇲🇻", "+960"),
        AdminCountryInfo("ML", "Mali", "🇲🇱", "+223"),
        AdminCountryInfo("MT", "Malta", "🇲🇹", "+356"),
        AdminCountryInfo("MU", "Mauritius", "🇲🇺", "+230"),
        AdminCountryInfo("MD", "Moldova", "🇲🇩", "+373"),
        AdminCountryInfo("MN", "Mongolia", "🇲🇳", "+976"),
        AdminCountryInfo("ME", "Montenegro", "🇲🇪", "+382"),
        AdminCountryInfo("MA", "Morocco", "🇲🇦", "+212"),
        AdminCountryInfo("MM", "Myanmar", "🇲🇲", "+95"),
        AdminCountryInfo("NA", "Namibia", "🇳🇦", "+264"),
        AdminCountryInfo("NL", "Netherlands", "🇳🇱", "+31"),
        AdminCountryInfo("NZ", "New Zealand", "🇳🇿", "+64"),
        AdminCountryInfo("NO", "Norway", "🇳🇴", "+47"),
        AdminCountryInfo("OM", "Oman", "🇴🇲", "+968"),
        AdminCountryInfo("PA", "Panama", "🇵🇦", "+507"),
        AdminCountryInfo("PY", "Paraguay", "🇵🇾", "+595"),
        AdminCountryInfo("PE", "Peru", "🇵🇪", "+51"),
        AdminCountryInfo("PL", "Poland", "🇵🇱", "+48"),
        AdminCountryInfo("PT", "Portugal", "🇵🇹", "+351"),
        AdminCountryInfo("QA", "Qatar", "🇶🇦", "+974"),
        AdminCountryInfo("RO", "Romania", "🇷🇴", "+40"),
        AdminCountryInfo("RW", "Rwanda", "🇷🇼", "+250"),
        AdminCountryInfo("SN", "Senegal", "🇸🇳", "+221"),
        AdminCountryInfo("RS", "Serbia", "🇷🇸", "+381"),
        AdminCountryInfo("SK", "Slovakia", "🇸🇰", "+421"),
        AdminCountryInfo("SI", "Slovenia", "🇸🇮", "+386"),
        AdminCountryInfo("SO", "Somalia", "🇸🇴", "+252"),
        AdminCountryInfo("SE", "Sweden", "🇸🇪", "+46"),
        AdminCountryInfo("CH", "Switzerland", "🇨🇭", "+41"),
        AdminCountryInfo("SY", "Syria", "🇸🇾", "+963"),
        AdminCountryInfo("TW", "Taiwan", "🇹🇼", "+886"),
        AdminCountryInfo("TJ", "Tajikistan", "🇹🇯", "+992"),
        AdminCountryInfo("TZ", "Tanzania", "🇹🇿", "+255"),
        AdminCountryInfo("TN", "Tunisia", "🇹🇳", "+216"),
        AdminCountryInfo("TM", "Turkmenistan", "🇹🇲", "+993"),
        AdminCountryInfo("UG", "Uganda", "🇺🇬", "+256"),
        AdminCountryInfo("UA", "Ukraine", "🇺🇦", "+380"),
        AdminCountryInfo("UY", "Uruguay", "🇺🇾", "+598"),
        AdminCountryInfo("UZ", "Uzbekistan", "🇺🇿", "+998"),
        AdminCountryInfo("VE", "Venezuela", "🇻🇪", "+58"),
        AdminCountryInfo("YE", "Yemen", "🇾🇪", "+967"),
        AdminCountryInfo("ZM", "Zambia", "🇿🇲", "+260"),
        AdminCountryInfo("ZW", "Zimbabwe", "🇿🇼", "+263")
    )

    fun findByCode(code: String): AdminCountryInfo? {
        return allCountries.find { it.code.equals(code, ignoreCase = true) }
    }

    fun search(query: String): List<AdminCountryInfo> {
        val q = query.trim().lowercase()
        if (q.isEmpty()) return allCountries
        return allCountries.filter {
            it.name.lowercase().contains(q) ||
            it.code.lowercase().contains(q) ||
            it.dialCode.lowercase().contains(q)
        }
    }
}
